### ISSUE TITLE
Unfortunately, this script doesn't work with old HP P2000G3. It would be really appreciated, to have it working for old HP MSA2312i, HP P2000G3. 

### ISSUE THREAD

**Issue by BroadbandCommunicationsNorth** [asand3r/zbx-hpmsa#15]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by BroadbandCommunicationsNorth** [comment]
Unfortunately, this script doesn't work with old HP P2000G3. It would be really appreciated, to have it working for old  HP MSA2312i, HPP2000G3.

**Comment by asand3r** [comment]
Hi @BroadbandCommunicationsNorth 
Could you provide more additional info? Because I received a couple feedbacks confirming the script works fine with the models you mentioned.

**Comment by BroadbandCommunicationsNorth** [comment]
Here is an example the request for  MSA2040 from Zabbix server:
[root@zabbix externalscripts]# ./zbx-hpmsa.py -u zabbix -p XXXXXXXXXXXXXX lld 10.16.25.77 vdisks
{"data":[{"{#VDISK.ID}":"BGroup1","{#VDISK.TYPE}":"Virtual"}]}

From the same Zabbix server for MSA2000:
[root@zabbix externalscripts]# ./zbx-hpmsa.py -u zabbix -p XXXXXXXXXXXXXX lld 10.16.25.75 vdisks
Traceback (most recent call last):
  File "./zbx-hpmsa.py", line 806, in <module>
    print(make_lld(MSA_CONNECT, args.part, skey))
  File "./zbx-hpmsa.py", line 355, in make_lld
    vdisk_type = vdisk.find("./PROPERTY[@name='storage-type']").text
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by asand3r** [comment]
@BroadbandCommunicationsNorth , OK, got it. Think, I can correct it, but it will be helpful if you can provide me XML output from P2000 API, because of I haven't this devices.
```bash
# set cli-parameters api
# show vdisks
```
This is should return XML with required needed data.

**Comment by WolfCrazy** [comment]
Hello.
I have msa 2000G3, Zabbix 4, and this script [zbx-hpmsa.py.gz](https://github.com/asand3r/zbx-hpmsa/files/2729328/zbx-hpmsa.py.gz)

Verion firmware msa: 
Controller A Versions
Bundle Version: TS201R015
Build Date: Wed Nov 10 13:45:04 MST 2010

Controller B Versions
Bundle Version: TS201R015
Build Date: Wed Nov 10 13:45:04 MST 2010


![msa](https://user-images.githubusercontent.com/46521078/50901936-9b685a00-142a-11e9-9aff-15b0cfa0d505.png)

MSA JSON controllers full:
`Traceback (most recent call last):  File "/usr/lib/zabbix/externalscripts/zbx-hpmsa.py", line 815, in <module>    print(get_full_json(MSA_CONNECT, args.part, skey))  File "/usr/lib/zabbix/externalscripts/zbx-hpmsa.py", line 587, in get_full_json    ctrl_rd_status = PROP.find("./PROPERTY[@name='redundancy-status']").textAttributeError: 'NoneType' object has no attribute 'text'`


MSA JSON disk-groups full:
`ERROR: -10025 : The command was not recognized.`


MSA JSON enclosures full:
`Traceback (most recent call last):  File "/usr/lib/zabbix/externalscripts/zbx-hpmsa.py", line 815, in <module>    print(get_full_json(MSA_CONNECT, args.part, skey))  File "/usr/lib/zabbix/externalscripts/zbx-hpmsa.py", line 471, in get_full_json    resp_return_code, resp_description, xml = query_xmlapi(url, sessionkey)  File "/usr/lib/zabbix/externalscripts/zbx-hpmsa.py", line 257, in query_xmlapi    response_xml = eTree.fromstring(response.content)  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1333, in XML    parser.feed(text)xml.etree.ElementTree.ParseError: junk after document element: line 1153, column 0`


MSA JSON fans full:
`ERROR: Cannot parse XML. 'NoneType' object has no attribute 'text'`

MSA JSON pools full:
`ERROR: Cannot parse XML. 'NoneType' object has no attribute 'text'`

MSA JSON power-supplies full:
`Traceback (most recent call last):
  File "/usr/lib/zabbix/externalscripts/zbx-hpmsa.py", line 815, in <module>
    print(get_full_json(MSA_CONNECT, args.part, skey))
  File "/usr/lib/zabbix/externalscripts/zbx-hpmsa.py", line 658, in get_full_json
    ps_dc12i = PS.find("./PROPERTY[@name='dc12i']").text
AttributeError: 'NoneType' object has no attribute 'text'`

MSA JSON volumes full:
`Traceback (most recent call last):
  File "/usr/lib/zabbix/externalscripts/zbx-hpmsa.py", line 815, in <module>
    print(get_full_json(MSA_CONNECT, args.part, skey))
  File "/usr/lib/zabbix/externalscripts/zbx-hpmsa.py", line 563, in get_full_json
    volume_health = PROP.find("./PROPERTY[@name='health']").text
AttributeError: 'NoneType' object has no attribute 'text'`

**Comment by asand3r** [comment]
OK, so we have two problems.
The first one is the old models of HPE MSA knows nothing about primitives like 'disk-groups', right? In that case we have errors like 'ERROR: -10025 : The command was not recognized.' I cannot fix it and you must correct it in your copy of template file.
The second problem is old MSA hasn't some parameters in XML, e.g. 'redundancy-status'. It give us errors like "'NoneType' object has no attribute 'text'" - it can be fixed, but I need a list of that properties, because of I haven't devices elder HPE MSA 2040 to check it in live. I'll check docs and try to fix it. Is it full list of such errors in your case?
  - Controller redundancy status: redundancy-status
  - Power Supply DC12i: dc12i
  - Volume health: health

About fans and pools - does 2000G3 knows anything about MSA pools? Fans should works fine...

**Comment by egisan2019** [comment]
Hi!
Trying to set the template ans script to and problems similar to above. "Error 1025" means you cannot do anything about it - too old firmware or hardware. Still, there are some errors, which I'd like you to help me to fix them
HP StorageWorks MSA Storage P2000 G3 SAS
Version:TS230P008

Latest data shows:
![image](https://user-images.githubusercontent.com/52775780/61030753-c6763b00-a3c6-11e9-9af4-5cdf417ddff5.png)

MSA JSON controllers full:
Traceback (most recent call last):  File "/usr/lib/zabbix/externalscripts/zbx-hpmsa.py", line 765, in <module>    print(get_full_json(MSA_CONNECT, args.part, skey))  File "/usr/lib/zabbix/externalscripts/zbx-hpmsa.py", line 556, in get_full_json    ctrl_rd_status_num = PROP.find("./PROPERTY[@name='redundancy-status-numeric']").textAttributeError: 'NoneType' object has no attribute 'text'

MSA JSON power-supplies full:
Traceback (most recent call last):
  File "/usr/lib/zabbix/externalscripts/zbx-hpmsa.py", line 765, in <module>
    print(get_full_json(MSA_CONNECT, args.part, skey))
  File "/usr/lib/zabbix/externalscripts/zbx-hpmsa.py", line 617, in get_full_json
    ps_dc12i = PS.find("./PROPERTY[@name='dc12i']").text
AttributeError: 'NoneType' object has no attribute 'text'

MSA JSON volumes full:
Traceback (most recent call last):
  File "/usr/lib/zabbix/externalscripts/zbx-hpmsa.py", line 765, in <module>
    print(get_full_json(MSA_CONNECT, args.part, skey))
  File "/usr/lib/zabbix/externalscripts/zbx-hpmsa.py", line 540, in get_full_json
    vol_health_num = PROP.find("./PROPERTY[@name='health-numeric']").text
AttributeError: 'NoneType' object has no attribute 'text'

I've attached XML's, that are generated from CLI - system gives the info away.
Any clues with box firmware update, which could solve Error 1025?
Any help would be appreciated.

[XML.zip](https://github.com/asand3r/zbx-hpmsa/files/3381113/XML.zip)

**Comment by zhukovd** [comment]
Hi!
I have P2000 G3 and i have same problem.
Did you find any solution to this problem?

**Comment by asand3r** [comment]
> Hi!
> I have P2000 G3 and i have same problem.
> Did you find any solution to this problem?

Hi, today v0.7.4 has been released where I fixed problem in LLD on P2000G3.

**Comment by shonconer** [comment]
Good afternoon, colleagues! There is a P2000 G3 FC shelf and could not take data either. I had to get into the script and tweak it a bit. I am attaching the edited script and template. I apologize in advance for the Cyrillic in the template.

We also managed to get data on the fans in the power supplies.

You can also use the original template, but you will have to remove many data elements from it.

[zbx-hpmsa-0.7.2.zip](https://github.com/asand3r/zbx-hpmsa/files/5275705/zbx-hpmsa-0.7.2.zip)

**Comment by vegagrey** [comment]
Good day,

I have the HP StorageWorks MSA2012i and have the same problems as P2000 G3.

Could you please find any solutions?
I can provide an XML file from MSA if needed.
