### ISSUE TITLE
error while executing item test

### ISSUE THREAD

**Issue by Vit-hev** [asand3r/zbx-hpmsa#41]
execution result is as follows

Traceback (most recent call last):
File "/usr/lib/zabbix/externalscripts/zbx-hpmsa.py", line 750, in <module>
skey = get_skey(MSA_CONNECT, CRED_HASH)
File "/usr/lib/zabbix/externalscripts/zbx-hpmsa.py", line 169, in get_skey
return get_skey(msa, hashed_login, use_cache=False)
File "/usr/lib/zabbix/externalscripts/zbx-hpmsa.py", line 174, in get_skey
ret_code, sessionkey, xml = query_xmlapi(url=url, sessionkey=None)
File "/usr/lib/zabbix/externalscripts/zbx-hpmsa.py", line 259, in query_xmlapi
response_xml = eTree.fromstring(response.content)
File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML
parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 5, column 13

please tell me what is the problem?

**Comment by MihaPik** [comment]
Traceback (most recent call last):
  File "./zbx-hpsma.py", line 673, in <module>
    skey = get_skey(MSA_CONNECT, CRED_HASH)
  File "./zbx-hpsma.py", line 154, in get_skey
    cur_timestamp = datetime.timestamp(datetime.utcnow())
AttributeError: type object 'datetime.datetime' has no attribute 'timestamp'

similar error
